# Generated by Django 3.1.3 on 2021-01-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_stud_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_ans',
            name='qna',
            field=models.JSONField(null=True),
        ),
    ]
