# Generated by Django 3.1.3 on 2021-05-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_user_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud_ans',
            name='stud_user',
        ),
        migrations.AddField(
            model_name='user',
            name='recorded_Ans',
            field=models.ManyToManyField(blank=True, related_name='recorded_Ans', to='quiz.Stud_Ans'),
        ),
    ]
